// <auto-generated />
namespace POST.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class efe_dev : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(efe_dev));
        
        string IMigrationMetadata.Id
        {
            get { return "202210220845127_efe_dev"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
