using System.ComponentModel;

namespace GIGLS.Core.Enums
{
    public enum ShipmentScanStatus
    {
        [Description("ARRIVAL SCAN AT SERVICE CENTER (TERMINAL PICK UP)")]
        ASP,

        [Description("DESTINATION DAILY SCAN AWAITING DELIVERY (TERMINAL PICK UP SHIPMENTS)")]
        ASPD,

        [Description("DESTINATION ARRIVAL SCAN (HOME DELIVERY SHIPMENTS)")]
        DASA,

        [Description("DESTINATION ARRIVAL SCAN (HOME DELIVERY SHIPMENTS)")]
        DASD,
        
        [Description("DESTINATION ARRIVAL SCAN (TERMINAL PICK UP SHIPMENTS)")]  
        DASP,

        [Description("DESTINATION DELIVERY SCAN (ALL SHIPMENTS)")]
        DDSA,

        [Description("DEPART SERVICE CENTER TO DESTINATION (HOME DELIVERY SHIPMENTS)")]
        DSCD,

        [Description("DEPART SERVICE CENTER TO GATEWAY FOR DELIVERY WITHIN ABUJA")]
        DSCDA,

        [Description("DEPART SERVICE CENTER TO GATEWAY FOR DELIVERY WITHIN LAGOS")]
        DSCDL,

        [Description("DEPART SERVICE CENTER TO GATEWAY LAGOS")]
        DSCG,

        [Description("DEPART SERVICE CENTER TO DESTINATION (TERMINAL PICK UP SHIPMENTS)")]
        DSCP,

        [Description("GATEWAY SHIPMENT ARRIVAL FROM ALL SERVICE CENTERS (HOME DELIVERY SHIPMENTS)")]
        GAH,

        [Description("GATEWAY SHIPMENT ARRIVAL FROM ALL SERVICE CENTERS (TERMINAL PICK UP SHIPMENTS)")]
        GAP,

        [Description("GATEWAY SHIPMENT DEPARTURE FOR DELIVERY")]
        GDD,

        [Description("GATEWAY SHIPMENT DEPARTURE TO ALL DESTINATIONS (HOME DELIVERY SHIPMENTS)")]
        GDH,

        [Description("GATEWAY SHIPMENT DEPARTURE TO ALL DESTINATIONS (TERMINAL PICK UP SHIPMENTS)")]
        GDP,

        [Description("SHIPMENT SCAN FOR RETURNS")]
        SSR,

        CRT, //1ST SCAN FOR EVERY SHIPMENT
        TRO, //WHEN YOU TRANSFER SHIPMENT FROM WHERE IT IS CREATED TO OPS CENTER WITHIN OR TO THE HUB
        ARO, //WHEN SHIPMENT ARRIVED THE OPS CENTER OR HUB FOR FURTHER PROCESSING
        DSC, //WHEN SHIPMENT DEPARTS SERVICE CENTER DIRECTLY TO DESTINATION
        DTR, //WHEN SHIPMENT DEPARTS SERVICE CENTER TO THE HUB OR ANOTHER CENTER THAT IS NOT THE FINAL DESTINATION
        AST, //WHEN SHIPMENT ARRIVES THE HUB OR ANOTHER CENTER THAT IS NOT THE FINAL DESTINATION
        DST, //WHEN SHIPMENT IN TRANSIT DEPARTS THE HUB OR ANOTHER CENTER THAT IS NOT THE FINAL DESTINATION
        ARP, //WHEN SHIPMENT ARRIVED THE HUB FOR FURTHER PROCESSING TO ANOTHER TRANSIT CENTER OR FINAL DESTINATION
        APT, // WHEN SHIPMENT IS ALREADY PROCESSED BUT IN TRANSIT THROUGH THE HUB
        DPC, //WHEN SHIPMENT DEPARTS PROCESSING CENTER
        ARF, //WHEN SHIPMENT ARRIVED FINAL DESTINATION
        AD, //DAILY SCAN UNTIL SHIPMENT IS DELIVERED
        OKT, //WHEN SHIPMENT IS DELIVERED AT THE TERMINAL TO THE RECEIVER
        GOP, //SCAN AT SERVICE CENTER WHEN SHIPMENT IS TRANSFERRED TO OPS FOR HOME DELIVERY
        WC, //SCAN BEFORE SHIPMENT IS TAKEN OUT FOR DELIVERY TO RECEIVER
        OKC //SCAN TO SHOW SHIPMENT HAS BEEN DELIVERED
    }
}
