// <auto-generated />
namespace GIGLS.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class deltalinetest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deltalinetest));
        
        string IMigrationMetadata.Id
        {
            get { return "202209200441266_deltaline+test"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
