//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class WarehouseReceipt {
    
    private System.DateTime createdOnField;
    
    private string numberField;
    
    private string createdByNameField;
    
    private byte versionField;
    
    private string issuedByNameField;
    
    private WarehouseReceiptIssuedBy issuedByField;
    
    private WarehouseReceiptIssuedByAddress1 issuedByAddressField;
    
    private string shipperNameField;
    
    private WarehouseReceiptShipper shipperField;
    
    private WarehouseReceiptShipperAddress1 shipperAddressField;
    
    private string consigneeNameField;
    
    private WarehouseReceiptConsignee consigneeField;
    
    private WarehouseReceiptConsigneeAddress1 consigneeAddressField;
    
    private string carrierNameField;
    
    private WarehouseReceiptCarrier carrierField;
    
    private string notesField;
    
    private WarehouseReceiptItems itemsField;
    
    private WarehouseReceiptMeasurementUnits measurementUnitsField;
    
    private ushort creatorNetworkIDField;
    
    private WarehouseReceiptEvent[] eventsField;
    
    private byte totalPiecesField;
    
    private WarehouseReceiptTotalWeight totalWeightField;
    
    private WarehouseReceiptTotalVolume totalVolumeField;
    
    private WarehouseReceiptTotalVolumeWeight totalVolumeWeightField;
    
    private WarehouseReceiptChargeableWeight chargeableWeightField;
    
    private WarehouseReceiptTotalValue totalValueField;
    
    private uint carrierTrackingNumberField;
    
    private string statusField;
    
    private bool hasAttachmentsField;
    
    private WarehouseReceiptBillingClient billingClientField;
    
    private byte lastItemIDField;
    
    private bool isOnlineField;
    
    private bool isLiquidatedField;
    
    private string gUIDField;
    
    private string typeField;
    
    /// <remarks/>
    public System.DateTime CreatedOn {
        get {
            return this.createdOnField;
        }
        set {
            this.createdOnField = value;
        }
    }
    
    /// <remarks/>
    public string Number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
    
    /// <remarks/>
    public string CreatedByName {
        get {
            return this.createdByNameField;
        }
        set {
            this.createdByNameField = value;
        }
    }
    
    /// <remarks/>
    public byte Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    public string IssuedByName {
        get {
            return this.issuedByNameField;
        }
        set {
            this.issuedByNameField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptIssuedBy IssuedBy {
        get {
            return this.issuedByField;
        }
        set {
            this.issuedByField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptIssuedByAddress1 IssuedByAddress {
        get {
            return this.issuedByAddressField;
        }
        set {
            this.issuedByAddressField = value;
        }
    }
    
    /// <remarks/>
    public string ShipperName {
        get {
            return this.shipperNameField;
        }
        set {
            this.shipperNameField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptShipper Shipper {
        get {
            return this.shipperField;
        }
        set {
            this.shipperField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptShipperAddress1 ShipperAddress {
        get {
            return this.shipperAddressField;
        }
        set {
            this.shipperAddressField = value;
        }
    }
    
    /// <remarks/>
    public string ConsigneeName {
        get {
            return this.consigneeNameField;
        }
        set {
            this.consigneeNameField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptConsignee Consignee {
        get {
            return this.consigneeField;
        }
        set {
            this.consigneeField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptConsigneeAddress1 ConsigneeAddress {
        get {
            return this.consigneeAddressField;
        }
        set {
            this.consigneeAddressField = value;
        }
    }
    
    /// <remarks/>
    public string CarrierName {
        get {
            return this.carrierNameField;
        }
        set {
            this.carrierNameField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptCarrier Carrier {
        get {
            return this.carrierField;
        }
        set {
            this.carrierField = value;
        }
    }
    
    /// <remarks/>
    public string Notes {
        get {
            return this.notesField;
        }
        set {
            this.notesField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptItems Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptMeasurementUnits MeasurementUnits {
        get {
            return this.measurementUnitsField;
        }
        set {
            this.measurementUnitsField = value;
        }
    }
    
    /// <remarks/>
    public ushort CreatorNetworkID {
        get {
            return this.creatorNetworkIDField;
        }
        set {
            this.creatorNetworkIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Event", IsNullable=false)]
    public WarehouseReceiptEvent[] Events {
        get {
            return this.eventsField;
        }
        set {
            this.eventsField = value;
        }
    }
    
    /// <remarks/>
    public byte TotalPieces {
        get {
            return this.totalPiecesField;
        }
        set {
            this.totalPiecesField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptTotalWeight TotalWeight {
        get {
            return this.totalWeightField;
        }
        set {
            this.totalWeightField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptTotalVolume TotalVolume {
        get {
            return this.totalVolumeField;
        }
        set {
            this.totalVolumeField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptTotalVolumeWeight TotalVolumeWeight {
        get {
            return this.totalVolumeWeightField;
        }
        set {
            this.totalVolumeWeightField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptChargeableWeight ChargeableWeight {
        get {
            return this.chargeableWeightField;
        }
        set {
            this.chargeableWeightField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptTotalValue TotalValue {
        get {
            return this.totalValueField;
        }
        set {
            this.totalValueField = value;
        }
    }
    
    /// <remarks/>
    public uint CarrierTrackingNumber {
        get {
            return this.carrierTrackingNumberField;
        }
        set {
            this.carrierTrackingNumberField = value;
        }
    }
    
    /// <remarks/>
    public string Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    public bool HasAttachments {
        get {
            return this.hasAttachmentsField;
        }
        set {
            this.hasAttachmentsField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptBillingClient BillingClient {
        get {
            return this.billingClientField;
        }
        set {
            this.billingClientField = value;
        }
    }
    
    /// <remarks/>
    public byte LastItemID {
        get {
            return this.lastItemIDField;
        }
        set {
            this.lastItemIDField = value;
        }
    }
    
    /// <remarks/>
    public bool IsOnline {
        get {
            return this.isOnlineField;
        }
        set {
            this.isOnlineField = value;
        }
    }
    
    /// <remarks/>
    public bool IsLiquidated {
        get {
            return this.isLiquidatedField;
        }
        set {
            this.isLiquidatedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string GUID {
        get {
            return this.gUIDField;
        }
        set {
            this.gUIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptIssuedBy {
    
    private string typeField;
    
    private string nameField;
    
    private System.DateTime createdOnField;
    
    private WarehouseReceiptIssuedByAddress addressField;
    
    private WarehouseReceiptIssuedByBillingAddress billingAddressField;
    
    private string emailField;
    
    private uint phoneField;
    
    private string accountNumberField;
    
    private ushort networkIDField;
    
    private bool isKnownShipperField;
    
    private bool isPrepaidField;
    
    private string gUIDField;
    
    /// <remarks/>
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime CreatedOn {
        get {
            return this.createdOnField;
        }
        set {
            this.createdOnField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptIssuedByAddress Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptIssuedByBillingAddress BillingAddress {
        get {
            return this.billingAddressField;
        }
        set {
            this.billingAddressField = value;
        }
    }
    
    /// <remarks/>
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    public uint Phone {
        get {
            return this.phoneField;
        }
        set {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    public string AccountNumber {
        get {
            return this.accountNumberField;
        }
        set {
            this.accountNumberField = value;
        }
    }
    
    /// <remarks/>
    public ushort NetworkID {
        get {
            return this.networkIDField;
        }
        set {
            this.networkIDField = value;
        }
    }
    
    /// <remarks/>
    public bool IsKnownShipper {
        get {
            return this.isKnownShipperField;
        }
        set {
            this.isKnownShipperField = value;
        }
    }
    
    /// <remarks/>
    public bool IsPrepaid {
        get {
            return this.isPrepaidField;
        }
        set {
            this.isPrepaidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string GUID {
        get {
            return this.gUIDField;
        }
        set {
            this.gUIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptIssuedByAddress {
    
    private string streetField;
    
    private string cityField;
    
    private string stateField;
    
    private uint zipCodeField;
    
    private string descriptionField;
    
    private uint contactPhoneField;
    
    private string contactEmailField;
    
    /// <remarks/>
    public string Street {
        get {
            return this.streetField;
        }
        set {
            this.streetField = value;
        }
    }
    
    /// <remarks/>
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public string State {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    public uint ZipCode {
        get {
            return this.zipCodeField;
        }
        set {
            this.zipCodeField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public uint ContactPhone {
        get {
            return this.contactPhoneField;
        }
        set {
            this.contactPhoneField = value;
        }
    }
    
    /// <remarks/>
    public string ContactEmail {
        get {
            return this.contactEmailField;
        }
        set {
            this.contactEmailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptIssuedByBillingAddress {
    
    private string streetField;
    
    private string cityField;
    
    private string stateField;
    
    private uint zipCodeField;
    
    private uint contactPhoneField;
    
    private string contactEmailField;
    
    /// <remarks/>
    public string Street {
        get {
            return this.streetField;
        }
        set {
            this.streetField = value;
        }
    }
    
    /// <remarks/>
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public string State {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    public uint ZipCode {
        get {
            return this.zipCodeField;
        }
        set {
            this.zipCodeField = value;
        }
    }
    
    /// <remarks/>
    public uint ContactPhone {
        get {
            return this.contactPhoneField;
        }
        set {
            this.contactPhoneField = value;
        }
    }
    
    /// <remarks/>
    public string ContactEmail {
        get {
            return this.contactEmailField;
        }
        set {
            this.contactEmailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptIssuedByAddress1 {
    
    private string streetField;
    
    private string cityField;
    
    private string stateField;
    
    private uint zipCodeField;
    
    private string descriptionField;
    
    private uint contactPhoneField;
    
    private string contactEmailField;
    
    /// <remarks/>
    public string Street {
        get {
            return this.streetField;
        }
        set {
            this.streetField = value;
        }
    }
    
    /// <remarks/>
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public string State {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    public uint ZipCode {
        get {
            return this.zipCodeField;
        }
        set {
            this.zipCodeField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public uint ContactPhone {
        get {
            return this.contactPhoneField;
        }
        set {
            this.contactPhoneField = value;
        }
    }
    
    /// <remarks/>
    public string ContactEmail {
        get {
            return this.contactEmailField;
        }
        set {
            this.contactEmailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptShipper {
    
    private string typeField;
    
    private string nameField;
    
    private System.DateTime createdOnField;
    
    private WarehouseReceiptShipperAddress addressField;
    
    private WarehouseReceiptShipperBillingAddress billingAddressField;
    
    private long phoneField;
    
    private WarehouseReceiptShipperPaymentTerms paymentTermsField;
    
    private WarehouseReceiptShipperOtherAddresses otherAddressesField;
    
    private bool isPrepaidField;
    
    private string gUIDField;
    
    /// <remarks/>
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime CreatedOn {
        get {
            return this.createdOnField;
        }
        set {
            this.createdOnField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptShipperAddress Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptShipperBillingAddress BillingAddress {
        get {
            return this.billingAddressField;
        }
        set {
            this.billingAddressField = value;
        }
    }
    
    /// <remarks/>
    public long Phone {
        get {
            return this.phoneField;
        }
        set {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptShipperPaymentTerms PaymentTerms {
        get {
            return this.paymentTermsField;
        }
        set {
            this.paymentTermsField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptShipperOtherAddresses OtherAddresses {
        get {
            return this.otherAddressesField;
        }
        set {
            this.otherAddressesField = value;
        }
    }
    
    /// <remarks/>
    public bool IsPrepaid {
        get {
            return this.isPrepaidField;
        }
        set {
            this.isPrepaidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string GUID {
        get {
            return this.gUIDField;
        }
        set {
            this.gUIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptShipperAddress {
    
    private string[] streetField;
    
    private string cityField;
    
    private WarehouseReceiptShipperAddressCountry countryField;
    
    private string descriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Street")]
    public string[] Street {
        get {
            return this.streetField;
        }
        set {
            this.streetField = value;
        }
    }
    
    /// <remarks/>
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptShipperAddressCountry Country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptShipperAddressCountry {
    
    private string codeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptShipperBillingAddress {
    
    private string[] streetField;
    
    private string cityField;
    
    private WarehouseReceiptShipperBillingAddressCountry countryField;
    
    private string descriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Street")]
    public string[] Street {
        get {
            return this.streetField;
        }
        set {
            this.streetField = value;
        }
    }
    
    /// <remarks/>
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptShipperBillingAddressCountry Country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptShipperBillingAddressCountry {
    
    private string codeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptShipperPaymentTerms {
    
    private string descriptionField;
    
    private byte netDueDaysField;
    
    private decimal discountPercentageField;
    
    private byte discountPaidDaysField;
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public byte NetDueDays {
        get {
            return this.netDueDaysField;
        }
        set {
            this.netDueDaysField = value;
        }
    }
    
    /// <remarks/>
    public decimal DiscountPercentage {
        get {
            return this.discountPercentageField;
        }
        set {
            this.discountPercentageField = value;
        }
    }
    
    /// <remarks/>
    public byte DiscountPaidDays {
        get {
            return this.discountPaidDaysField;
        }
        set {
            this.discountPaidDaysField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptShipperOtherAddresses {
    
    private WarehouseReceiptShipperOtherAddressesAddress addressField;
    
    /// <remarks/>
    public WarehouseReceiptShipperOtherAddressesAddress Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptShipperOtherAddressesAddress {
    
    private string streetField;
    
    private string cityField;
    
    private string stateField;
    
    private uint zipCodeField;
    
    private string descriptionField;
    
    private string contactNameField;
    
    private ulong contactPhoneField;
    
    /// <remarks/>
    public string Street {
        get {
            return this.streetField;
        }
        set {
            this.streetField = value;
        }
    }
    
    /// <remarks/>
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public string State {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    public uint ZipCode {
        get {
            return this.zipCodeField;
        }
        set {
            this.zipCodeField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string ContactName {
        get {
            return this.contactNameField;
        }
        set {
            this.contactNameField = value;
        }
    }
    
    /// <remarks/>
    public ulong ContactPhone {
        get {
            return this.contactPhoneField;
        }
        set {
            this.contactPhoneField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptShipperAddress1 {
    
    private string streetField;
    
    private string cityField;
    
    private string stateField;
    
    private uint zipCodeField;
    
    private string descriptionField;
    
    private string contactNameField;
    
    private ulong contactPhoneField;
    
    /// <remarks/>
    public string Street {
        get {
            return this.streetField;
        }
        set {
            this.streetField = value;
        }
    }
    
    /// <remarks/>
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public string State {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    public uint ZipCode {
        get {
            return this.zipCodeField;
        }
        set {
            this.zipCodeField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string ContactName {
        get {
            return this.contactNameField;
        }
        set {
            this.contactNameField = value;
        }
    }
    
    /// <remarks/>
    public ulong ContactPhone {
        get {
            return this.contactPhoneField;
        }
        set {
            this.contactPhoneField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptConsignee {
    
    private string typeField;
    
    private string nameField;
    
    private System.DateTime createdOnField;
    
    private WarehouseReceiptConsigneeAddress addressField;
    
    private WarehouseReceiptConsigneeBillingAddress billingAddressField;
    
    private long phoneField;
    
    private WarehouseReceiptConsigneePaymentTerms paymentTermsField;
    
    private WarehouseReceiptConsigneeOtherAddresses otherAddressesField;
    
    private bool isPrepaidField;
    
    private string gUIDField;
    
    /// <remarks/>
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime CreatedOn {
        get {
            return this.createdOnField;
        }
        set {
            this.createdOnField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptConsigneeAddress Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptConsigneeBillingAddress BillingAddress {
        get {
            return this.billingAddressField;
        }
        set {
            this.billingAddressField = value;
        }
    }
    
    /// <remarks/>
    public long Phone {
        get {
            return this.phoneField;
        }
        set {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptConsigneePaymentTerms PaymentTerms {
        get {
            return this.paymentTermsField;
        }
        set {
            this.paymentTermsField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptConsigneeOtherAddresses OtherAddresses {
        get {
            return this.otherAddressesField;
        }
        set {
            this.otherAddressesField = value;
        }
    }
    
    /// <remarks/>
    public bool IsPrepaid {
        get {
            return this.isPrepaidField;
        }
        set {
            this.isPrepaidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string GUID {
        get {
            return this.gUIDField;
        }
        set {
            this.gUIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptConsigneeAddress {
    
    private string[] streetField;
    
    private string cityField;
    
    private WarehouseReceiptConsigneeAddressCountry countryField;
    
    private string descriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Street")]
    public string[] Street {
        get {
            return this.streetField;
        }
        set {
            this.streetField = value;
        }
    }
    
    /// <remarks/>
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptConsigneeAddressCountry Country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptConsigneeAddressCountry {
    
    private string codeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptConsigneeBillingAddress {
    
    private string[] streetField;
    
    private string cityField;
    
    private WarehouseReceiptConsigneeBillingAddressCountry countryField;
    
    private string descriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Street")]
    public string[] Street {
        get {
            return this.streetField;
        }
        set {
            this.streetField = value;
        }
    }
    
    /// <remarks/>
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptConsigneeBillingAddressCountry Country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptConsigneeBillingAddressCountry {
    
    private string codeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptConsigneePaymentTerms {
    
    private string descriptionField;
    
    private byte netDueDaysField;
    
    private decimal discountPercentageField;
    
    private byte discountPaidDaysField;
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public byte NetDueDays {
        get {
            return this.netDueDaysField;
        }
        set {
            this.netDueDaysField = value;
        }
    }
    
    /// <remarks/>
    public decimal DiscountPercentage {
        get {
            return this.discountPercentageField;
        }
        set {
            this.discountPercentageField = value;
        }
    }
    
    /// <remarks/>
    public byte DiscountPaidDays {
        get {
            return this.discountPaidDaysField;
        }
        set {
            this.discountPaidDaysField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptConsigneeOtherAddresses {
    
    private WarehouseReceiptConsigneeOtherAddressesAddress addressField;
    
    /// <remarks/>
    public WarehouseReceiptConsigneeOtherAddressesAddress Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptConsigneeOtherAddressesAddress {
    
    private string streetField;
    
    private string cityField;
    
    private string stateField;
    
    private uint zipCodeField;
    
    private string descriptionField;
    
    private string contactNameField;
    
    private ulong contactPhoneField;
    
    /// <remarks/>
    public string Street {
        get {
            return this.streetField;
        }
        set {
            this.streetField = value;
        }
    }
    
    /// <remarks/>
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public string State {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    public uint ZipCode {
        get {
            return this.zipCodeField;
        }
        set {
            this.zipCodeField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string ContactName {
        get {
            return this.contactNameField;
        }
        set {
            this.contactNameField = value;
        }
    }
    
    /// <remarks/>
    public ulong ContactPhone {
        get {
            return this.contactPhoneField;
        }
        set {
            this.contactPhoneField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptConsigneeAddress1 {
    
    private string[] streetField;
    
    private string cityField;
    
    private WarehouseReceiptConsigneeAddressCountry1 countryField;
    
    private string descriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Street")]
    public string[] Street {
        get {
            return this.streetField;
        }
        set {
            this.streetField = value;
        }
    }
    
    /// <remarks/>
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptConsigneeAddressCountry1 Country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptConsigneeAddressCountry1 {
    
    private string codeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptCarrier {
    
    private string typeField;
    
    private string nameField;
    
    private System.DateTime createdOnField;
    
    private bool isPrepaidField;
    
    private WarehouseReceiptCarrierCarrierInfo carrierInfoField;
    
    private string gUIDField;
    
    /// <remarks/>
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime CreatedOn {
        get {
            return this.createdOnField;
        }
        set {
            this.createdOnField = value;
        }
    }
    
    /// <remarks/>
    public bool IsPrepaid {
        get {
            return this.isPrepaidField;
        }
        set {
            this.isPrepaidField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptCarrierCarrierInfo CarrierInfo {
        get {
            return this.carrierInfoField;
        }
        set {
            this.carrierInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string GUID {
        get {
            return this.gUIDField;
        }
        set {
            this.gUIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptCarrierCarrierInfo {
    
    private string carrierTypeCodeField;
    
    /// <remarks/>
    public string CarrierTypeCode {
        get {
            return this.carrierTypeCodeField;
        }
        set {
            this.carrierTypeCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptItems {
    
    private WarehouseReceiptItemsItem itemField;
    
    /// <remarks/>
    public WarehouseReceiptItemsItem Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptItemsItem {
    
    private byte versionField;
    
    private string statusField;
    
    private byte piecesField;
    
    private string descriptionField;
    
    private decimal pieceQuantityField;
    
    private bool isSummarizedField;
    
    private string warehouseReceiptGUIDField;
    
    private string pickupOrderGUIDField;
    
    private string packageNameField;
    
    private byte wHRItemIDField;
    
    private WarehouseReceiptItemsItemLength lengthField;
    
    private WarehouseReceiptItemsItemHeight heightField;
    
    private WarehouseReceiptItemsItemWidth widthField;
    
    private WarehouseReceiptItemsItemWeight weightField;
    
    private bool containedPiecesWeightIncludedField;
    
    private WarehouseReceiptItemsItemVolume volumeField;
    
    private WarehouseReceiptItemsItemVolumeWeight volumeWeightField;
    
    private WarehouseReceiptItemsItemPieceWeight pieceWeightField;
    
    private WarehouseReceiptItemsItemPieceVolume pieceVolumeField;
    
    private WarehouseReceiptItemsItemPackage packageField;
    
    private string outShipmentGUIDField;
    
    private bool includeInSEDField;
    
    private bool isContainerField;
    
    private string outHouseWayBillNumberField;
    
    private byte lastReceptionNetworkIDField;
    
    private string shipmentTypeField;
    
    private System.DateTime outDateField;
    
    private string warehouseReceiptNumberField;
    
    private string pickupOrderNumberField;
    
    private byte orderIndexField;
    
    private bool isPalletField;
    
    private bool isOverstockField;
    
    private bool notLoadedField;
    
    private bool inTaskField;
    
    private WarehouseReceiptItemsItemPreviousLocation previousLocationField;
    
    private System.DateTime entryDateField;
    
    private string gUIDField;
    
    private string typeField;
    
    /// <remarks/>
    public byte Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    public string Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    public byte Pieces {
        get {
            return this.piecesField;
        }
        set {
            this.piecesField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public decimal PieceQuantity {
        get {
            return this.pieceQuantityField;
        }
        set {
            this.pieceQuantityField = value;
        }
    }
    
    /// <remarks/>
    public bool IsSummarized {
        get {
            return this.isSummarizedField;
        }
        set {
            this.isSummarizedField = value;
        }
    }
    
    /// <remarks/>
    public string WarehouseReceiptGUID {
        get {
            return this.warehouseReceiptGUIDField;
        }
        set {
            this.warehouseReceiptGUIDField = value;
        }
    }
    
    /// <remarks/>
    public string PickupOrderGUID {
        get {
            return this.pickupOrderGUIDField;
        }
        set {
            this.pickupOrderGUIDField = value;
        }
    }
    
    /// <remarks/>
    public string PackageName {
        get {
            return this.packageNameField;
        }
        set {
            this.packageNameField = value;
        }
    }
    
    /// <remarks/>
    public byte WHRItemID {
        get {
            return this.wHRItemIDField;
        }
        set {
            this.wHRItemIDField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptItemsItemLength Length {
        get {
            return this.lengthField;
        }
        set {
            this.lengthField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptItemsItemHeight Height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptItemsItemWidth Width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptItemsItemWeight Weight {
        get {
            return this.weightField;
        }
        set {
            this.weightField = value;
        }
    }
    
    /// <remarks/>
    public bool ContainedPiecesWeightIncluded {
        get {
            return this.containedPiecesWeightIncludedField;
        }
        set {
            this.containedPiecesWeightIncludedField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptItemsItemVolume Volume {
        get {
            return this.volumeField;
        }
        set {
            this.volumeField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptItemsItemVolumeWeight VolumeWeight {
        get {
            return this.volumeWeightField;
        }
        set {
            this.volumeWeightField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptItemsItemPieceWeight PieceWeight {
        get {
            return this.pieceWeightField;
        }
        set {
            this.pieceWeightField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptItemsItemPieceVolume PieceVolume {
        get {
            return this.pieceVolumeField;
        }
        set {
            this.pieceVolumeField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptItemsItemPackage Package {
        get {
            return this.packageField;
        }
        set {
            this.packageField = value;
        }
    }
    
    /// <remarks/>
    public string OutShipmentGUID {
        get {
            return this.outShipmentGUIDField;
        }
        set {
            this.outShipmentGUIDField = value;
        }
    }
    
    /// <remarks/>
    public bool IncludeInSED {
        get {
            return this.includeInSEDField;
        }
        set {
            this.includeInSEDField = value;
        }
    }
    
    /// <remarks/>
    public bool IsContainer {
        get {
            return this.isContainerField;
        }
        set {
            this.isContainerField = value;
        }
    }
    
    /// <remarks/>
    public string OutHouseWayBillNumber {
        get {
            return this.outHouseWayBillNumberField;
        }
        set {
            this.outHouseWayBillNumberField = value;
        }
    }
    
    /// <remarks/>
    public byte LastReceptionNetworkID {
        get {
            return this.lastReceptionNetworkIDField;
        }
        set {
            this.lastReceptionNetworkIDField = value;
        }
    }
    
    /// <remarks/>
    public string ShipmentType {
        get {
            return this.shipmentTypeField;
        }
        set {
            this.shipmentTypeField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime OutDate {
        get {
            return this.outDateField;
        }
        set {
            this.outDateField = value;
        }
    }
    
    /// <remarks/>
    public string WarehouseReceiptNumber {
        get {
            return this.warehouseReceiptNumberField;
        }
        set {
            this.warehouseReceiptNumberField = value;
        }
    }
    
    /// <remarks/>
    public string PickupOrderNumber {
        get {
            return this.pickupOrderNumberField;
        }
        set {
            this.pickupOrderNumberField = value;
        }
    }
    
    /// <remarks/>
    public byte OrderIndex {
        get {
            return this.orderIndexField;
        }
        set {
            this.orderIndexField = value;
        }
    }
    
    /// <remarks/>
    public bool IsPallet {
        get {
            return this.isPalletField;
        }
        set {
            this.isPalletField = value;
        }
    }
    
    /// <remarks/>
    public bool IsOverstock {
        get {
            return this.isOverstockField;
        }
        set {
            this.isOverstockField = value;
        }
    }
    
    /// <remarks/>
    public bool NotLoaded {
        get {
            return this.notLoadedField;
        }
        set {
            this.notLoadedField = value;
        }
    }
    
    /// <remarks/>
    public bool InTask {
        get {
            return this.inTaskField;
        }
        set {
            this.inTaskField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptItemsItemPreviousLocation PreviousLocation {
        get {
            return this.previousLocationField;
        }
        set {
            this.previousLocationField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime EntryDate {
        get {
            return this.entryDateField;
        }
        set {
            this.entryDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string GUID {
        get {
            return this.gUIDField;
        }
        set {
            this.gUIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptItemsItemLength {
    
    private string unitField;
    
    private decimal valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptItemsItemHeight {
    
    private string unitField;
    
    private decimal valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptItemsItemWidth {
    
    private string unitField;
    
    private decimal valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptItemsItemWeight {
    
    private string unitField;
    
    private decimal valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptItemsItemVolume {
    
    private string unitField;
    
    private decimal valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptItemsItemVolumeWeight {
    
    private string unitField;
    
    private decimal valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptItemsItemPieceWeight {
    
    private string unitField;
    
    private decimal valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptItemsItemPieceVolume {
    
    private string unitField;
    
    private decimal valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptItemsItemPackage {
    
    private string typeField;
    
    private string codeField;
    
    private string nameField;
    
    /// <remarks/>
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public string Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptItemsItemPreviousLocation {
    
    private string descriptionField;
    
    private string typeField;
    
    private ushort networkIDField;
    
    private string warehouseZoneNameField;
    
    private bool isDisabledField;
    
    private string codeField;
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public ushort NetworkID {
        get {
            return this.networkIDField;
        }
        set {
            this.networkIDField = value;
        }
    }
    
    /// <remarks/>
    public string WarehouseZoneName {
        get {
            return this.warehouseZoneNameField;
        }
        set {
            this.warehouseZoneNameField = value;
        }
    }
    
    /// <remarks/>
    public bool IsDisabled {
        get {
            return this.isDisabledField;
        }
        set {
            this.isDisabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptMeasurementUnits {
    
    private string lengthUnitField;
    
    private string volumeUnitField;
    
    private string weightUnitField;
    
    private string volumeWeightUnitField;
    
    private string areaUnitField;
    
    private byte lengthPrecisionField;
    
    private byte volumePrecisionField;
    
    private byte weightPrecisionField;
    
    private byte volumeWeightPrecisionField;
    
    private byte areaPrecisionField;
    
    private decimal volumeWeightFactorField;
    
    /// <remarks/>
    public string LengthUnit {
        get {
            return this.lengthUnitField;
        }
        set {
            this.lengthUnitField = value;
        }
    }
    
    /// <remarks/>
    public string VolumeUnit {
        get {
            return this.volumeUnitField;
        }
        set {
            this.volumeUnitField = value;
        }
    }
    
    /// <remarks/>
    public string WeightUnit {
        get {
            return this.weightUnitField;
        }
        set {
            this.weightUnitField = value;
        }
    }
    
    /// <remarks/>
    public string VolumeWeightUnit {
        get {
            return this.volumeWeightUnitField;
        }
        set {
            this.volumeWeightUnitField = value;
        }
    }
    
    /// <remarks/>
    public string AreaUnit {
        get {
            return this.areaUnitField;
        }
        set {
            this.areaUnitField = value;
        }
    }
    
    /// <remarks/>
    public byte LengthPrecision {
        get {
            return this.lengthPrecisionField;
        }
        set {
            this.lengthPrecisionField = value;
        }
    }
    
    /// <remarks/>
    public byte VolumePrecision {
        get {
            return this.volumePrecisionField;
        }
        set {
            this.volumePrecisionField = value;
        }
    }
    
    /// <remarks/>
    public byte WeightPrecision {
        get {
            return this.weightPrecisionField;
        }
        set {
            this.weightPrecisionField = value;
        }
    }
    
    /// <remarks/>
    public byte VolumeWeightPrecision {
        get {
            return this.volumeWeightPrecisionField;
        }
        set {
            this.volumeWeightPrecisionField = value;
        }
    }
    
    /// <remarks/>
    public byte AreaPrecision {
        get {
            return this.areaPrecisionField;
        }
        set {
            this.areaPrecisionField = value;
        }
    }
    
    /// <remarks/>
    public decimal VolumeWeightFactor {
        get {
            return this.volumeWeightFactorField;
        }
        set {
            this.volumeWeightFactorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptEvent {
    
    private System.DateTime dateField;
    
    private WarehouseReceiptEventEventDefinition eventDefinitionField;
    
    private bool includeInTrackingField;
    
    private string ownerTypeField;
    
    private string ownerNumberField;
    
    private string ownerGUIDField;
    
    /// <remarks/>
    public System.DateTime Date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptEventEventDefinition EventDefinition {
        get {
            return this.eventDefinitionField;
        }
        set {
            this.eventDefinitionField = value;
        }
    }
    
    /// <remarks/>
    public bool IncludeInTracking {
        get {
            return this.includeInTrackingField;
        }
        set {
            this.includeInTrackingField = value;
        }
    }
    
    /// <remarks/>
    public string OwnerType {
        get {
            return this.ownerTypeField;
        }
        set {
            this.ownerTypeField = value;
        }
    }
    
    /// <remarks/>
    public string OwnerNumber {
        get {
            return this.ownerNumberField;
        }
        set {
            this.ownerNumberField = value;
        }
    }
    
    /// <remarks/>
    public string OwnerGUID {
        get {
            return this.ownerGUIDField;
        }
        set {
            this.ownerGUIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptEventEventDefinition {
    
    private string nameField;
    
    private bool includeInTrackingField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public bool IncludeInTracking {
        get {
            return this.includeInTrackingField;
        }
        set {
            this.includeInTrackingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptTotalWeight {
    
    private string unitField;
    
    private decimal valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptTotalVolume {
    
    private string unitField;
    
    private decimal valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptTotalVolumeWeight {
    
    private string unitField;
    
    private decimal valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptChargeableWeight {
    
    private string unitField;
    
    private decimal valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptTotalValue {
    
    private string currencyField;
    
    private decimal valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Currency {
        get {
            return this.currencyField;
        }
        set {
            this.currencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptBillingClient {
    
    private string typeField;
    
    private string nameField;
    
    private System.DateTime createdOnField;
    
    private WarehouseReceiptBillingClientAddress addressField;
    
    private WarehouseReceiptBillingClientBillingAddress billingAddressField;
    
    private long phoneField;
    
    private WarehouseReceiptBillingClientPaymentTerms paymentTermsField;
    
    private WarehouseReceiptBillingClientOtherAddresses otherAddressesField;
    
    private bool isPrepaidField;
    
    private string gUIDField;
    
    /// <remarks/>
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime CreatedOn {
        get {
            return this.createdOnField;
        }
        set {
            this.createdOnField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptBillingClientAddress Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptBillingClientBillingAddress BillingAddress {
        get {
            return this.billingAddressField;
        }
        set {
            this.billingAddressField = value;
        }
    }
    
    /// <remarks/>
    public long Phone {
        get {
            return this.phoneField;
        }
        set {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptBillingClientPaymentTerms PaymentTerms {
        get {
            return this.paymentTermsField;
        }
        set {
            this.paymentTermsField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptBillingClientOtherAddresses OtherAddresses {
        get {
            return this.otherAddressesField;
        }
        set {
            this.otherAddressesField = value;
        }
    }
    
    /// <remarks/>
    public bool IsPrepaid {
        get {
            return this.isPrepaidField;
        }
        set {
            this.isPrepaidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string GUID {
        get {
            return this.gUIDField;
        }
        set {
            this.gUIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptBillingClientAddress {
    
    private string[] streetField;
    
    private string cityField;
    
    private WarehouseReceiptBillingClientAddressCountry countryField;
    
    private string descriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Street")]
    public string[] Street {
        get {
            return this.streetField;
        }
        set {
            this.streetField = value;
        }
    }
    
    /// <remarks/>
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptBillingClientAddressCountry Country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptBillingClientAddressCountry {
    
    private string codeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptBillingClientBillingAddress {
    
    private string[] streetField;
    
    private string cityField;
    
    private WarehouseReceiptBillingClientBillingAddressCountry countryField;
    
    private string descriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Street")]
    public string[] Street {
        get {
            return this.streetField;
        }
        set {
            this.streetField = value;
        }
    }
    
    /// <remarks/>
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public WarehouseReceiptBillingClientBillingAddressCountry Country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptBillingClientBillingAddressCountry {
    
    private string codeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptBillingClientPaymentTerms {
    
    private string descriptionField;
    
    private byte netDueDaysField;
    
    private decimal discountPercentageField;
    
    private byte discountPaidDaysField;
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public byte NetDueDays {
        get {
            return this.netDueDaysField;
        }
        set {
            this.netDueDaysField = value;
        }
    }
    
    /// <remarks/>
    public decimal DiscountPercentage {
        get {
            return this.discountPercentageField;
        }
        set {
            this.discountPercentageField = value;
        }
    }
    
    /// <remarks/>
    public byte DiscountPaidDays {
        get {
            return this.discountPaidDaysField;
        }
        set {
            this.discountPaidDaysField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptBillingClientOtherAddresses {
    
    private WarehouseReceiptBillingClientOtherAddressesAddress addressField;
    
    /// <remarks/>
    public WarehouseReceiptBillingClientOtherAddressesAddress Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WarehouseReceiptBillingClientOtherAddressesAddress {
    
    private string streetField;
    
    private string cityField;
    
    private string stateField;
    
    private uint zipCodeField;
    
    private string descriptionField;
    
    private string contactNameField;
    
    private ulong contactPhoneField;
    
    /// <remarks/>
    public string Street {
        get {
            return this.streetField;
        }
        set {
            this.streetField = value;
        }
    }
    
    /// <remarks/>
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public string State {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    public uint ZipCode {
        get {
            return this.zipCodeField;
        }
        set {
            this.zipCodeField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string ContactName {
        get {
            return this.contactNameField;
        }
        set {
            this.contactNameField = value;
        }
    }
    
    /// <remarks/>
    public ulong ContactPhone {
        get {
            return this.contactPhoneField;
        }
        set {
            this.contactPhoneField = value;
        }
    }
}
